apiVersion: v1
kind: Service
metadata:
  name: penpot-nodeport
  namespace: penpot
spec:
  type: NodePort
  selector:
    app: penpot-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080   # penpot internal port
      nodePort: 30080    # port exposed on EC2 nodes

