# inventory.ini template files

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# ---- #
# PROD #
# ---- #

[tower]
penpot-tower-az1 ansible_host=51.44.165.41 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/bastion-sshkey
penpot-tower-az2 ansible_host=15.188.239.65 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/bastion-sshkey

[bastion]
penpot-bastion-az1 ansible_host=51.44.165.41 ansible_user=bastion ansible_ssh_private_key_file=~/.ssh/bastion-sshkey
penpot-bastion-az2 ansible_host=15.188.239.65 ansible_user=bastion ansible_ssh_private_key_file=~/.ssh/bastion-sshkey

[traefik]
penpot-traefik-az1 ansible_host=10.0.1.130 leader=true ansible_user=admin ansible_ssh_private_key_file=~/.ssh/traefik-sshkey
penpot-traefik-az2 ansible_host=10.0.2.27 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/traefik-sshkey

[monitoring]
penpot-prometheus-az1 ansible_host=10.0.11.43 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/prometheus-sshkey
penpot-premetheus-az2 ansible_host=10.0.12.204 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/prometheus-sshkey

[k3s_prd_masters]
k3s-master-1 ansible_host=10.0.11.179 master=true ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey
k3s-master-2 ansible_host=10.0.12.236 master=true ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_prd_master_3a]
k3s-master-1 ansible_host=10.0.11.179 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_prd_master_3b]
k3s-master-2 ansible_host=10.0.12.236 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_prd_master_slave_3a]
k3s-slave-1 ansible_host=10.0.11.174 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey
k3s-slave-2 ansible_host=10.0.11.221 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_prd_master_slave_3b]
k3s-slave-3 ansible_host=10.0.12.125 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey
k3s-slave-4 ansible_host=10.0.12.90 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_prd_masters_slave:children]
k3s_prd_master_slave_3a
k3s_prd_master_slave_3b


# ------- #
# Staging #
# ------- #

[k3s_stg_masters]
k3s-stg-master-1 ansible_host=10.0.21.92 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey 
k3s-stg-master-2 ansible_host=10.0.22.104 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_stg_master_3a]
k3s-stg-master-1 ansible_host=10.0.21.92 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_stg_master_3b]
k3s-stg-master-2 ansible_host=10.0.22.104 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_stg_worker_3a]
k3s-stg-worker-1 ansible_host=10.0.21.185 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_stg_worker_3b]
k3s-stg-worker-2 ansible_host=10.0.22.231 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[k3s_stg_workers:children]
k3s_stg_worker_3a
k3s_stg_worker_3b

[penpot_stg_az1]
10.0.21.92 master=true ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey
10.0.21.185 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

[penpot_stg_az2]
10.0.22.104 master=true ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey
10.0.22.231 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/k3s-sshkey

