services:
  app:
    image: app_image
    build: ./app 
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - db_volume:/var/lib/mysql

  db:
    image: db_image
    build: ./db
    hostname: molok
    ports:
      - "3306:3306"


volumes: 
  db_volume: {}
      

    